name: smart_delivery

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: db_delivery
    restart: always
    environment:
      POSTGRES_DB: smart_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jppp5734
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
  backend-app:
    restart: on-failure
    build: .
    container_name: app_delivery
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/smart_delivery
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Jppp5734
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
volumes:
  postgres-data:
