name: smart_delivery

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: db_delivery
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_delivery
    ports:
      - "6379:6379"

  jenkins:
    image: jenkins/jenkins:lts
    user: root  # Required to access the docker socket
    ports:
      - "8085:8082"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  backend-app:
    restart: on-failure
    build: .
    container_name: app_delivery
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_REPOSITORIES_ENABLED=false
    env_file:
      - .env
volumes:
  postgres-data:
  jenkins_home:
